### ISSUE TITLE
Render to a specific place

### ISSUE THREAD

**Issue by amenk** [TalAter/SpeechKITT#3]
Is it possible to do something like
    vroom('#hereItGoes'); 
to render the interface to a certain `<div>` ?

It looks like I have to call the method right now at the place I want it which is not easy in my case, as I load the Javascript at the page's bottom.

**Comment by rolero** [comment]
Same here. Would be great to be able to create at a certain location more easily.

**Comment by TalAter** [comment]
@amenk , @rolero: Could you explain the use case for this? What you are trying to achieve, are you doing this with a new theme you created, etc.

This will help me implement this in a way that is most helpful to as many people as possible.

Thank you.

**Comment by amenk** [comment]
yes, to include into an existing page

**Comment by TalAter** [comment]
I understand that, but can you explain why you need it in a certain `div`? Are you using a custom theme? The existing themes position the UI with `absolute` position on the page, so which div they are in will make no difference.

**Comment by amenk** [comment]
I forgot it ... :-) Currently I am not using it - maybe later ...

**Comment by TalAter** [comment]
@rolero - If you can help with the use case for this, please comment below and I will reopen the issue.

**Comment by rolero** [comment]
For sure I have a use case :) Sorry for the slow response but I am working in China. Have a look at the following website: https://beta.medai.io/

Currently I removed KITT but actually I wanted it where  the "Get Started" button is located. I was only able to load it in the left below corner or I need to adjust the theme.

What I would like to do, is that I give a certain element an id like <div id="loadkitthere"></div> . The button I replace with this div.

Then using jQuery I activate Kitt. For example when the website/document is loaded:

$(document).ready(function () {
$('#loadkitthere').SpeechKITT.vroom(); //Just a sample.
});

Then the Kitt GUI is located where this div is located and moves when the divs moves( for example when responsive CSS kicks in). The GUI itself was already great. I like the button a lot.

Another question. Do you have any experience with connecting KITT with IBM Watson conversations? I am currently developing a WEBAPI that will work as a middleware solution, so that I can store data and also can execute other functions like showing certain data etc. For a BETA I actually want to connect it with IBM Watson directly.

Best regards,

Ron
